blank_issues_enabled: false
contact_links:
    - name: Contributing to iltransfer
      url: https://github.com/YisusChrist/iltransfer/blob/main/CONTRIBUTING.md
      about: Guidelines for how to report an issue.
    - name: Support
      url: https://github.com/YisusChrist/iltransfer/discussions
      about: Ask the community for support
    - name: Documentation
      url: https://github.com/YisusChrist/iltransfer/wiki
      about: Many questions might be already answered here.
